server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///withjpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver